application: my-shopping-lists
api_version: 1
threadsafe: false
version: 6
runtime: python27

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app
  login: required
  secure: always

libraries:
- name: jinja2
  version: latest
